### ISSUE TITLE
Issue with "--task regression" in main.py

### ISSUE THREAD

**Issue by zchiang** [clara-genomics/AtacWorks#101]
I am seeing the following error when I run main.py with "--task regression":

```
INFO:2020-01-15 22:21:43,021:AtacWorks-main] Checkng input files for compatibility
Building model: resnet ...
Loading model weights from /home/ubuntu/AtacWorks/data/pretrained_models/model_best.pth.tar...
Finished loading.
Finished building.
Process Process-2:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/AtacWorks/main.py", line 462, in writer
    item = res_queue.get()
  File "<string>", line 2, in get
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/managers.py", line 796, in _callmethod
    kind, result = conn.recv()
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/ubuntu/AtacWorks/main.py", line 660, in <module>
    main()
  File "/home/ubuntu/AtacWorks/main.py", line 649, in main
    worker(args.gpu, ngpus_per_node, args, res_queue)
  File "/home/ubuntu/AtacWorks/main.py", line 336, in infer_worker
    print_freq=args.print_freq, res_queue=res_queue, pad=args.pad, transform=args.transform)
  File "/home/ubuntu/AtacWorks/claragenomics/dl4atac/train/infer.py", line 77, in infer
    batch_res = np.expand_dims(pred.cpu().numpy(), axis=-1)                    
AttributeError: 'tuple' object has no attribute 'cpu'
```

Here is the command I am running:

```
python $root_dir/main.py --infer \
        --infer_files $out_dir/$2/$2.h5 \
        --intervals_file $3 \
        --sizes_file $ref_dir/hg19.chrom.sizes \
        --weights_path $saved_model_dir/$4 \
        --out_home $out_dir/$2 \
        --label $2_1M_pretrained \
        --result_fname $2_1M_pretrained \
        --model resnet \
        --nblocks 5 \
        --nfilt 15 \
        --width 51 \
        --dil 8 \
        --nblocks_cla 2 \
        --nfilt_cla 15 \
        --width_cla 51 \
        --dil_cla 8 \
        --task regression \
        --num_workers 8 \
        --gen_bigwig \
        --pad 5000 \
        --bs 512
```

If I run the same command, but change "regression" to "both" then it seems to run without issues. Let me know if I can provide any other info.

**Comment by tijyojwad** [comment]
@ntadimeti can you take a look?

**Comment by zchiang** [comment]
should mention I'm on branch dev-v0.2.0

**Comment by avantikalal** [comment]
Currently it is not possible to run --model resnet with any task other than 'both'. The resnet is designed to perform both tasks. @zchiang I'd suggest running it with `--both` and ignore the classification output if it's not useful. If runtime is an issue for you we can discuss that separately.

**Comment by zchiang** [comment]
Ah okay. Yes, let's discuss elsewhere.
